import { type Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ActiveLink } from "./components/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex items-center justify-between bg-gray-800 p-4 text-white">
					<h1 className="text-2xl font-bold">My Shop</h1>
					<ul className="flex gap-4">
						<li>
							<ActiveLink href="/">Home</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products">All</ActiveLink>
						</li>
					</ul>
				</nav>
				<section className="mx-auto max-w-7xl px-4 py-12">{children}</section>
				<footer>
					<p className="text-center text-sm text-gray-600">© {new Date().getFullYear()} </p>
				</footer>
			</body>
		</html>
	);
}
